server:
  servlet:
    context-path: /experiment
spring:
　　datasource:
  　　type: com.alibaba.druid.pool.DruidDataSource
  　　driver-class-name: org.gjt.mm.mysql.Driver
  　　url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
  　　username: root
  　　password: 123456
  　　filters: stat,wall,log4j
  　　dbcp2:
    　　min-idle: 5
    　　initial-size: 5
    　　max-total: 5
    　　max-wait-millis: 200